### ISSUE TITLE
incomplete url in readme.md

### ISSUE THREAD

**Issue by culturetogo** [grandgeorg/docker-omeka-s#1]
Dear Viktor,

I think the following url in readme.md

To access the PHPMyAdmin web interface, open your web browser and navigate to http://localhost:8080

should be:

To access the PHPMyAdmin web interface, open your web browser and navigate to http://localhost:8080/phpmyadmin/ (?)

Best, Michael

**Comment by culturetogo** [comment]
Sorry, I didn't realize there's a difference in port (8000 vs. 8080). I assume the url you gave was correct.

**Comment by grandgeorg** [comment]
The URL for PMA `http://localhost:8080` is indeed correct the way it is.
It will only be different when you set it in a reverse proxy (e.g. Apache) to a subdirectory:

```apacheconf 
ProxyPass /phpmyadmin/  http://localhost:8080/
ProxyPassReverse /phpmyadmin/ http://localhost:8080/
```
